name: Base Image

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/base.yml'
      - 'docker/Dockerfile.base'
      - 'docker/Dockerfile.base.dockerignore'
      - 'docker/Dockerfile.base-dev'
      - 'docker/Dockerfile.base-dev.dockerignore'
      - 'pyproject.toml'
      - 'poetry.lock'
  schedule:
    - cron:  '30 5 */14 * *'

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build base image
        run: docker build -t ghcr.io/emfcamp/website-base:latest -f ./docker/Dockerfile.base .
      - name: Publish base image
        run: docker push ghcr.io/emfcamp/website-base:latest
      - name: Build base-dev image
        run: docker buildx build -t ghcr.io/emfcamp/website-base-dev:latest -f ./docker/Dockerfile.base-dev --push --platform=linux/amd64,linux/arm64 .
