name: Deploy

on: 
  push:
    branches:
      - main

env:
  COMPOSE_INTERACTIVE_NO_CLI: 1

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      COVERALLS_GIT_BRANCH: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v1
      - name: Fetch latest docker-compose
        run: sudo curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - name: Build containers
        run: docker-compose -f ./docker-compose.yml -f ./docker-compose.ci.yml build --parallel
      - name: Start environment
        run: docker-compose -f ./docker-compose.yml -f ./docker-compose.ci.yml up -d
      - name: Test
        run: docker-compose -f ./docker-compose.yml -f ./docker-compose.ci.yml exec -T app poetry run make test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build app image
        run: docker buildx build -t ghcr.io/emfcamp/website:latest -f ./Dockerfile.prod --push --platform=linux/amd64,linux/arm64  .
      - name: Build static image
        run: docker buildx build -t ghcr.io/emfcamp/website-static:latest -f ./docker/static/Dockerfile --push --platform=linux/amd64,linux/arm64 ./docker/static/
